PeopleManager/Models/ErrorViewModel.cs
namespace PeopleManager.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

PeopleManager/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using PeopleManager.Models;
using PeopleManager.Services;

namespace PeopleManager.Controllers
{
	public class HomeController : Controller
	{
		private readonly PersonService _personService;

		public HomeController(PersonService personService)
        {
            _personService = personService;
        }

		public IActionResult Index()
		{
			var people = _personService.Find();
			return View(people);
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

PeopleManager/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManager.Model;
using PeopleManager.Services;

namespace PeopleManager.Controllers
{
	public class PeopleController : Controller
	{
		private readonly PersonService _personService;

		public PeopleController(PersonService personService)
		{
            _personService = personService;
		}

		[HttpGet]
		public IActionResult Index()
		{
			var people = _personService.Find();
			return View(people);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Person person)
		{
            if (!ModelState.IsValid)
            {
				return View(person);
            }

            var newPerson = _personService.Create(person);
            if (newPerson is null)
            {
				ModelState.AddModelError("", "Something went wrong");
                return View(person);
            }

			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Edit(int id)
        {
            var person = _personService.Get(id);

			if (person is null)
			{
				return RedirectToAction("Index");
			}
			
			return View(person);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit([FromRoute]int id, [FromForm]Person person)
		{
			if (!ModelState.IsValid)
			{
				return View(person);
			}

            var dbPerson = _personService.Update(id, person);

			if (dbPerson is null)
			{
                ModelState.AddModelError("", "Something went wrong");
                return View(person);
			}
			
			return RedirectToAction("Index");
		}

		[HttpGet]
        public IActionResult Delete(int id)
        {
            var person = _personService.Get(id);
            if (person is null)
            {
                return RedirectToAction("Index");
            }
			
            return View(person);
        }

        [HttpPost("People/Delete/{id?}")]
		[ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _personService.Delete(id);
            return RedirectToAction("Index");
        }

		
	}
}

PeopleManager/Views/Home/Index.cshtml
@model IList<Person>
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Welcome</h1>
	<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@if (Model.Any())
{
    <div class="text-center">
        <h1 class="display-4">Employee of the Month</h1>
        <partial name="PersonCardPartial" model="Model.First()"/>
    </div>
}


<div class="text-center">
	<h1 class="display-4">People</h1>
	<div class="row">
		@foreach (var person in Model)
		{
			<div class="col-lg-4 col-12">
				<partial name="PersonCardPartial" model="person"/>
			</div>
		}
	</div>
</div>

PeopleManager/Views/Home/PersonCardPartial.cshtml
@model Person
<div class="card">
	<div class="card-header">
		<h2 class="card-title">@Model.FirstName @Model.LastName</h2>
	</div>
	<div class="card-body">
		<a href="mailto:@Model.Email">@Model.Email</a>
	</div>
</div>

PeopleManager/Views/People/Create.cshtml
@model Person

@{
	ViewData["Title"] = "Create new Person";
}

<div class="text-center">
	<h1 class="display-4">@ViewData["Title"]</h1>
</div>

<form method="post">
	<partial name="PersonCreateEditPartial" model="Model"/>
	<button type="submit" class="btn btn-primary">Create</button>
</form>

PeopleManager/Views/People/Delete.cshtml
@model Person

@{
    ViewData["Title"] = "Delete Person";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
</div>

<p>Are you sure you want to delete @Model.FirstName @Model.LastName (@Model.Email)</p>

<form method="post">
    <a class="btn btn-light" asp-action="Index">No</a>
    <button class="btn btn-warning" type="submit">Yes</button>
</form>

PeopleManager/Views/People/Edit.cshtml
@model Person

@{
	ViewData["Title"] = "Edit Person";
}

<div class="text-center">
	<h1 class="display-4">@ViewData["Title"]</h1>
</div>

<form method="post">
	<partial name="PersonCreateEditPartial" model="Model" />
	<button type="submit" class="btn btn-primary">Edit</button>
</form>

PeopleManager/Views/People/Index.cshtml
@model IList<Person>

@{
	ViewData["Title"] = "Manage People";
}

<div class="text-center">
	<h1 class="display-4">@ViewData["Title"]</h1>
</div>

<a asp-action="Create" class="btn btn-primary">Create new</a>

<table class="table">
    <thead>
    <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var person in Model)
    {
        <partial name="PersonRowPartial" model="person"/>
    }
    </tbody>
</table>

<div id="deleteModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Person</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this person.</p>
            </div>
            <div class="modal-footer">
                <form asp-action="DeleteConfirmed" method="post">
                    <input type="hidden" name="id"/>
                    <a class="btn btn-light" data-dismiss="modal">No</a>
                    <button class="btn btn-warning" type="submit">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(function() {
            $("[data-role=Delete]").on("click",
                function() {
                    let id = $(this).data("id");
                    $(".modal input[name=id]").val(id);
                });
        });
    </script>
}

PeopleManager/Views/People/PersonCreateEditPartial.cshtml
@model Person

<div asp-validation-summary="ModelOnly"></div>

<div class="form-group">
	<label asp-for="FirstName"></label>
	<input asp-for="FirstName" class="form-control">
	<span asp-validation-for="FirstName"></span>
</div>
<div class="form-group">
	<label asp-for="LastName"></label>
	<input asp-for="LastName" class="form-control">
	<span asp-validation-for="LastName"></span>
</div>
<div class="form-group">
	<label asp-for="Email"></label>
	<input asp-for="Email" class="form-control">
	<span asp-validation-for="Email"></span>
</div>

PeopleManager/Views/People/PersonRowPartial.cshtml
@model Person
<tr>
	<td>@Model.FirstName</td>
	<td>@Model.LastName</td>
	<td><a href="mailto:@Model.Email">@Model.Email</a></td>
	<td>
		<a class="btn btn-outline-info" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        <a class="btn btn-outline-warning" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
        <button class="btn btn-outline-warning" 
           data-role="Delete" 
           data-id="@Model.Id"
           data-toggle="modal" 
           data-target="#deleteModal">Delete with modal</button>
	</td>
</tr>

PeopleManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleManager_Eras1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeopleManager_Eras1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">Manage people</a>
	                    </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PeopleManager_Eras1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>